library(lattice)

x_cex=y_cex=1.5
x_lab_cex=y_lab_cex=1.55
col=c("dark green", "dark blue")

##########################################
## Fig. 3A (Venn Diagriam)
# Generated by hand using the numbers specified in Venn.R

##########################################
## Fig. 3B (Barplot indicating overlap with active marks)

getOverlap <- function(mark, k562=NULL, gm12878=NULL, hela=NULL, cd4=NULL, jurkat=NULL, mcf7=NULL, folder="histones") {
  pre <- "wgEncodeBroadHistone"
  post <- "StdAln.bb"
  frac.mark.peaks.in.dreg <- double(0)
  frac.dreg.in.mark <- double(0)
  
  ## K562
  if(!is.null(k562) | folder=="histones") {
   k562_path <- paste("/usr/data/GROseq.parser/hg19/k562/",folder,"/", sep="")
   if(is.null(k562)) k562 <- paste(pre, "K562", mark, post, sep="")
   system(paste("bigBedToBed ",paste(k562_path, k562, sep="")," tmp2.bed"))
   system(paste("cat tmp2.bed | sort-bed - > tmp.bed"))
   
   total_k <- as.double(system("grep '' -c tmp.bed", intern=TRUE))
   overlap_k <- as.double(system("bedmap --indicator tmp.bed k562.bed | grep '1' -c ", intern=TRUE)) ## #mark peaks in dREG
   frac.mark.peaks.in.dreg <- c(frac.mark.peaks.in.dreg, k562= overlap_k/total_k)
   
   total_k_dreg <- as.double(system("grep '' -c k562.bed", intern=TRUE))
   overlap_k_dreg <- as.double(system("bedmap --indicator k562.bed tmp.bed | grep '1' -c ", intern=TRUE)) ## #dreg peaks in mark
   frac.dreg.in.mark <- c(frac.dreg.in.mark, k562= overlap_k_dreg/total_k_dreg)
  } 
  
  ## GM12878
  if(!is.null(gm12878) | folder=="histones") {
   gm12878_path <- paste("/usr/data/GROseq.parser/hg19/gm12878/",folder,"/", sep="")
   if(is.null(gm12878)) gm12878 <- paste(pre, "Gm12878", mark, post, sep="")
   system(paste("bigBedToBed ",paste(gm12878_path, gm12878, sep="")," tmp2.bed"))
   system(paste("cat tmp2.bed | sort-bed - > tmp.bed"))
   
   total_g <- as.double(system("grep '' -c tmp.bed", intern=TRUE))
   overlap_g <- as.double(system("bedmap --indicator tmp.bed gm12878.bed | grep '1' -c ", intern=TRUE)) ## #mark peaks in dREG
   frac.mark.peaks.in.dreg<- c(frac.mark.peaks.in.dreg, gm12878= overlap_g/total_g)
  
   total_g_dreg <- as.double(system("grep '' -c gm12878.bed", intern=TRUE))
   overlap_g_dreg <- as.double(system("bedmap --indicator gm12878.bed tmp.bed | grep '1' -c ", intern=TRUE)) ## #dreg peaks in mark
   frac.dreg.in.mark <- c(frac.dreg.in.mark, gm12878= overlap_g_dreg/total_g_dreg)
  } 
  
  ## cd4
  if(!is.null(cd4)) {
   cd4_path <- paste("/usr/data/GROseq.parser/hg19/cd4/",tolower(mark),"/", sep="")
   cd4 <- paste(tolower(mark), ".peaks_peaks.narrowPeak", sep="")
   system(paste("cat ",paste(cd4_path, cd4, sep=""),"  | sort-bed - > tmp.bed"))
   
   total_g <- as.double(system("grep '' -c tmp.bed", intern=TRUE))
   overlap_g <- as.double(system("bedmap --indicator tmp.bed cd4.bed | grep '1' -c ", intern=TRUE)) ## #mark peaks in dREG
   frac.mark.peaks.in.dreg<- c(frac.mark.peaks.in.dreg, cd4= overlap_g/total_g)
  
   total_g_dreg <- as.double(system("grep '' -c cd4.bed", intern=TRUE))
   overlap_g_dreg <- as.double(system("bedmap --indicator cd4.bed tmp.bed | grep '1' -c ", intern=TRUE)) ## #dreg peaks in mark
   frac.dreg.in.mark <- c(frac.dreg.in.mark, cd4= overlap_g_dreg/total_g_dreg)
  } 
  
  ## mcf7
  if(!is.null(mcf7)) {
   mcf7_path <- paste("/usr/data/GROseq.parser/hg19/mcf7/",folder,"/", sep="")
   system(paste("zcat ",paste(mcf7_path, mcf7, sep="")," | sort-bed - > tmp.bed"))
	  
   total_g <- as.double(system("grep '' -c tmp.bed", intern=TRUE))
   overlap_g <- as.double(system("bedmap --indicator tmp.bed mcf7.bed | grep '1' -c ", intern=TRUE)) ## #mark peaks in dREG
   frac.mark.peaks.in.dreg<- c(frac.mark.peaks.in.dreg, mcf7= overlap_g/total_g)
  
   total_g_dreg <- as.double(system("grep '' -c mcf7.bed", intern=TRUE))
   overlap_g_dreg <- as.double(system("bedmap --indicator mcf7.bed tmp.bed | grep '1' -c ", intern=TRUE)) ## #dreg peaks in mark
   frac.dreg.in.mark <- c(frac.dreg.in.mark, mcf7= overlap_g_dreg/total_g_dreg)
  } 
  
  ## hela
  if(!is.null(hela)) {
   hela_path <- paste("/usr/data/GROseq.parser/hg19/hela/histone_peaks/", sep="")
   hela <- paste(pre, "Helas3", mark, post, sep="")
   system(paste("bigBedToBed ",paste(hela_path, hela, sep="")," tmp2.bed"))
   system(paste("cat tmp2.bed | sort-bed - > tmp.bed"))
   
   total_g <- as.double(system("grep '' -c tmp.bed", intern=TRUE))
   overlap_g <- as.double(system("bedmap --indicator tmp.bed hela.bed | grep '1' -c ", intern=TRUE)) ## #mark peaks in dREG
   frac.mark.peaks.in.dreg<- c(frac.mark.peaks.in.dreg, hela= overlap_g/total_g)
  
   total_g_dreg <- as.double(system("grep '' -c hela.bed", intern=TRUE))
   overlap_g_dreg <- as.double(system("bedmap --indicator hela.bed tmp.bed | grep '1' -c ", intern=TRUE)) ## #dreg peaks in mark
   frac.dreg.in.mark <- c(frac.dreg.in.mark, hela= overlap_g_dreg/total_g_dreg)
  }
  
  if(!is.null(jurkat)) {
   jurkat_path <- paste("/usr/data/GROseq.parser/hg19/jurkat/histone_peaks/", sep="")
   jurkat <- paste("wgEncodeUwHistoneJurkat", mark, post, sep="")
   system(paste("bigBedToBed ",paste(jurkat_path, jurkat, sep="")," tmp2.bed"))
   system(paste("cat tmp2.bed | sort-bed - > tmp.bed"))
   
   total_g <- as.double(system("grep '' -c tmp.bed", intern=TRUE))
   overlap_g <- as.double(system("bedmap --indicator tmp.bed jurkat.bed | grep '1' -c ", intern=TRUE)) ## #mark peaks in dREG
   frac.mark.peaks.in.dreg<- c(frac.mark.peaks.in.dreg, jurkat= overlap_g/total_g)
  
   total_g_dreg <- as.double(system("grep '' -c jurkat.bed", intern=TRUE))
   overlap_g_dreg <- as.double(system("bedmap --indicator jurkat.bed tmp.bed | grep '1' -c ", intern=TRUE)) ## #dreg peaks in mark
   frac.dreg.in.mark <- c(frac.dreg.in.mark, jurkat= overlap_g_dreg/total_g_dreg)
  }

  Color = "#777777"
  if(folder=="histones") Color = "#DD9999"
  if(folder=="tf_peaks") Color = "#9999DD"
  if(mark=="Tbp"|mark=="Taf1") Color = "#99DD99"
  return(list(Name=mark, frac.mark.peaks.in.dreg= frac.mark.peaks.in.dreg*100, 
						frac.dreg.in.mark= frac.dreg.in.mark*100, col= Color))
}

source("~/src/featureDetector/test_functions/figures/histplot.R")

## TFBS:
tfs <- read.table("/usr/data/GROseq.parser/hg19/k562/tf_peaks/tf_names_and_files.txt")
tfs_list <- list()
for(i in 1:NROW(tfs)) {
  tfs_list[[i]] <- getOverlap(as.character(tfs$V1[i]), file_k= tfs$V2[i], folder="tf_peaks")
}

## Histone mods.
histones <- list()

histones[[1]] <- getOverlap("H3k27ac", mcf7="GSM945854_hg19_wgEncodeSydhHistoneMcf7H3k27acUcdPk.narrowPeak.gz", hela="h3k27ac") ## H3k27ac
histones[[2]] <- getOverlap("H3k9ac", hela="h3k9ac", cd4="h3k9ac") ## H3k9ac ... mcf7="H3K9ac.liftOver.peaks.bed.gz", 
histones[[3]] <- getOverlap("H2az")
histones[[4]] <- getOverlap("H3k4me1", cd4="h3k4me1") ## mcf7="H3K4me1.liftOver.peaks.bed.gz", 
histones[[5]] <- getOverlap("H3k4me2", hela="h3k4me2")
histones[[6]] <- getOverlap("H3k4me3", cd4="h3k4me3", hela="h3k4me3", jurkat="h3k4me3") ## mcf7="H3K4me3.liftOver.peaks.bed.gz", 

fillCols <- c(k562= "#FF7171", gm12878= "#0000C7", mcf7= "#7FCE9D", ac16= "#7476BE", cd4= "#81CD49", jurkat= "#586036", hela= "#513646") #c(k562=	"#ff7171",gm12878="#0000c7")

#getOverlap("H4k20me1")

assays <- list()
assays[[1]] <- list(Name= "DNAse-1", frac.mark.peaks.in.dreg= c(27, 27), frac.dreg.in.mark=c(0,0), col="#dddddd")
assays[[2]] <- list(Name= "chromHMM", frac.mark.peaks.in.dreg= c(22, 22), frac.dreg.in.mark=c(0,0), col="#389cff")

pdf("Fig3ac.pdf")

	slices <- c(64, 42, (64+42)-100)
	lbls <- c("Enhancer", "Promoter", "Both")
	pie(slices, labels = lbls, main="dREG regions intersecting promoter or enhancers annotated by chromHMM")

 histplot(histones, fillCols)
 histplot(assays, fillCols)
 histplot(c(histones, assays), fillCols)
dev.off()

overlap <- read.csv(text="Mark, Overlap
DNAse-1, 27
chromHMM, 22
H3K27ac, 72
H3K9ac, 86", header=TRUE)

barchart(Overlap~Mark,data=overlap, col="dark blue",
         scales=list(x=list(rot=65,cex=x_cex), y=list(rot=0, cex=y_cex)), ylim=c(0,100), ylab="Fraction of Sites Transcribed",
		 auto.key=list(columns = 2, space = "top"),
		 lwd=1, pch=1, xlab= list(cex=x_lab_cex))
